import os
import subprocess
import json
import asyncio
import tempfile
import uuid

ZK_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "zk"))

def generate_zk_proof(age: int, is_married: bool, children: int, income: int, is_disabled: bool, public_score: int) -> dict:
    """
    Executes ZoKrates CLI to compute the circuit witness and generate Groth16 ZK proof.
    Uses temporary isolated files per request to prevent race conditions during concurrent execution.
    Returns the proof dictionary containing proof points (A, B, C) and public inputs.
    """
    married_str = "1" if is_married else "0"
    disabled_str = "1" if is_disabled else "0"
    
    with tempfile.TemporaryDirectory() as tmp_dir:
        witness_path = os.path.join(tmp_dir, f"witness_{uuid.uuid4().hex}")
        proof_path = os.path.join(tmp_dir, f"proof_{uuid.uuid4().hex}.json")

        witness_cmd = [
            "zokrates", "compute-witness",
            "-i", os.path.join(ZK_DIR, "out"),
            "-o", witness_path,
            "-a", str(age), married_str, str(children), str(income), disabled_str, str(public_score)
        ]
        
        try:
            subprocess.run(witness_cmd, check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            error_msg = e.stdout if e.stdout else e.stderr
            raise Exception(f"Failed to compute witness in ZK circuit: {error_msg.strip()}")

        proof_cmd = [
            "zokrates", "generate-proof",
            "-i", os.path.join(ZK_DIR, "out"),
            "-w", witness_path,
            "-p", os.path.join(ZK_DIR, "proving.key"),
            "-j", proof_path
        ]
        
        try:
            subprocess.run(proof_cmd, check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            error_msg = e.stdout if e.stdout else e.stderr
            raise Exception(f"Failed to generate ZK proof: {error_msg.strip()}")

        if not os.path.exists(proof_path):
            raise FileNotFoundError("proof.json was not generated by ZoKrates.")
            
        with open(proof_path, "r") as f:
            proof_data = json.load(f)
            
        return proof_data

async def async_generate_zk_proof(age: int, is_married: bool, children: int, income: int, is_disabled: bool, public_score: int) -> dict:
    """
    Asynchronous wrapper delegating ZoKrates CLI execution to a background thread pool.
    """
    return await asyncio.to_thread(
        generate_zk_proof, age, is_married, children, income, is_disabled, public_score
    )