import os
import subprocess
import json

ZK_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "zk"))

def generate_zk_proof(age: int, is_married: bool, children: int, income: int, is_disabled: bool, public_score: int) -> dict:
    """
    Executes ZoKrates via Docker to calculate the witness and generate the ZK Proof.
    Returns the JSON proof object containing the cryptographic keys.
    """
    # 1. Map python boolean to ZoKrates string input ("true"/"false")
    married_str = "1" if is_married else "0"
    disabled_str = "1" if is_disabled else "0"
    
    # 2. Run compute-witness natively
    witness_cmd = [
        "zokrates", "compute-witness",
        "-i", os.path.join(ZK_DIR, "out"),
        "-o", os.path.join(ZK_DIR, "witness"),
        "-a", str(age), married_str, str(children), str(income), disabled_str, str(public_score)
    ]
    
    try:
        subprocess.run(witness_cmd, check=True, capture_output=True)
    except subprocess.CalledProcessError as e:
        raise Exception(f"Failed to compute witness in ZK circuit: {e.stderr.decode()}")

    # 3. Run generate-proof natively
    proof_cmd = [
        "zokrates", "generate-proof",
        "-i", os.path.join(ZK_DIR, "out"),
        "-w", os.path.join(ZK_DIR, "witness"),
        "-p", os.path.join(ZK_DIR, "proving.key"),
        "-j", os.path.join(ZK_DIR, "proof.json")
    ]
    
    try:
        subprocess.run(proof_cmd, check=True, capture_output=True)
    except subprocess.CalledProcessError as e:
        raise Exception(f"Failed to generate ZK proof: {e.stderr.decode()}")

    # 4. Read generated proof.json
    proof_path = os.path.join(ZK_DIR, "proof.json")
    if not os.path.exists(proof_path):
        raise FileNotFoundError("proof.json was not generated by ZoKrates.")
        
    with open(proof_path, "r") as f:
        proof_data = json.load(f)
        
    return proof_data
